### ISSUE TITLE
Download broken

### ISSUE THREAD

**Issue by Amunak** [ahnet-69/Releases#2]
The [YAAP-15-VANILLA-HOMEMADE-pdx206-20241219.zip](https://sourceforge.net/projects/ahnet/files/YAAP/20241219/pdx206/YAAP-15-VANILLA-HOMEMADE-pdx206-20241219.zip/download) download seems to be broken - it never finishes downloading / times out (tried different browsers and even devices/OSes to download it; the recovery works fine). Seems to be a SourceForge issue.

Any chance of hosting it literally anywhere else (like here on GH)? SF is really shitty.

**Comment by realahnet** [comment]
i am afraid its just your internet connection. Sourceforge sucks. Unfortunately github wont let me post builds over 2gb otherwise i would love to leave them here on github. 

You can use a perhaps download manager like 1DM on android or FDM on windows to regenerate the link and replace it when it stops downloading

**Comment by Amunak** [comment]
This is so shit OMG I don't get it... So after some more testing I can say that SourceForge seems to not allow me to finish any of the bigger downloads, no matter what downloader or device I use. Switching to a VPN in Germany worked, for some reason, and also sped up the download (wtf, why?). I hate it so, so much.

Could you perhaps upload it to Mega, or something like that? Or maybe even just splitting it into 2GB chunks for GitHub, oldschool-style (where needed; I mean, I only want the 1.5GB file lol). Like I get this is a big ask but FFS I can't believe how shit SF is.

Edit: just to clarify: not even swapping the URL / resuming by the end helped, only the VPN fixed the issue. And the reason why I ask for an alternative is so that eventual updates are gonna be easier.

**Comment by realahnet** [comment]
yeah im sorry i want to preserve older builds and a whole record of them. we have limited storage on clouds like mega and stuff so its not possible. :( sorry 

i will try to look for a better alternative later but for now ig people have to cope
